/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/LumiBot.glb --transform 
Files: public/models/LumiBot.glb [23.53MB] > /home/dtic2025/DTIC/BASE/backend/TESIS/Frontend/LumiBot-transformed.glb [314.68KB] (99%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/LumiBot-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" scale={0.01}>
          <primitive object={nodes.Hips} />
        </group>
        <skinnedMesh name="char1" geometry={nodes.char1.geometry} material={materials.Material_1} skeleton={nodes.char1.skeleton} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/LumiBot-transformed.glb')
